name: ci

on:
  push:
    branches:
      - 'dev' # Add the develop branch to trigger the workflow
env:
      CI: true
      ENVIRONMENT: dev
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bhargav809/dotnet-poc:dotnet

      - name: Set env to dev
        if: endsWith(github.ref, '/dev')
        run: |
          echo "::set-env name=ENVIRONMENT::dev"

      - name: Set env to staging
        if: endsWith(github.ref, '/dev')
        run: |
          echo "::set-env name=ENVIRONMENT::staging"
          
      - name: Set env to production
        if: endsWith(github.ref, '/dev')
        run: |
          echo "::set-env name=ENVIRONMENT::production"
