name: ci

on:
  push:
    branches: [staging]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Compile
       run: Windows

  deploydev:
    name: Deploy to dev
    if: github.event.ref == 'pull request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - name: dev
      run: echo Iam deploying!

  deploystaging:
    name: Deploy to staging
    if: github.event.ref == 'ref/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - name: deploy
        run: echo Iam deploying!

      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: dev
        run: echo Rini is Deploying!

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bhargav809/dotnet-poc:dotnet
