name: ci

on:
  push:
    branches:
      - 'dev' # Add the develop branch to trigger the workflow
#env:
       #CI: True
       #ENVIRONMENT: dev
     
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bhargav809/dotnet-poc:dotnet
    
      - name: Deploy to Dev
        if: github.event_name == 'pull_request'
        needs: [Build]
        runs-on: ubuntu-latest
        environment: 
          name: Deployment
          url: 'http://dev.myapp.com'
        steps:
         - name: Deploy
           run: echo This is Deployment!

      - name: Deploy to Staging
        if: github.event_name == 'refs/heads/dev'
        needs: [Build]
        runs-on: ubuntu-latest
        environment: 
          name: Staging
          url: 'http://test.myapp.com'
        steps:
         - name: Stage
           run: echo This is Staging!
          
     
