name: ci

on:
  push:
    branches: [dev]
  pull_request:  
    branches: [dev]
  workflow_dispatch:  
  
jobs:
  deploydev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: dev
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      #- name: Setup .NET
       # uses: actions/setup-dotnet@v7.0.201
        #with:
         # dotnet-version: '3.1'  

      #- name: Restore Dependencies
       # run: dotnet restore

     # - name: Build
      #  run: dotnet build --configuration Release 
      
    steps:
      - name: Deploy
        run: echo I am Deploying!
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bhargav809/dotnet-poc:dotnet
