name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bhargav809/dotnet-poc:dotnet
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-54-163-139-35.compute-1.amazonaws.com 'docker pull bhargav809/dotnet-poc:dotnet'
          ssh ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-54-163-139-35.compute-1.amazonaws.com 'docker run -d --name testing -p 80:80 bhargav809/dotnet-poc:dotnet'
